version: '3'
services:
    web:
        image: nginx:alpine
        container_name: nginx
        volumes:
          - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./conf/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
          - "./conf/ssl:/etc/ssl"
          - "./app:/var/www/html"
        ports:
          - "80:80"
          - "443:443"
        environment:
          - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#        restart: always
        depends_on:
          - php
          - mysql
        links:
          - php
        networks:
          - app-network
    php:
        build: ./conf/php
        image: php-fpm
        container_name: php
#        restart: always
        volumes:
            - "./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/html"
#        working_dir: /var/www/html
        networks:
          - app-network
    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "./app:/app"
        command: install
        networks:
          - app-network
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
            - PMA_PORT=3306
#        restart: always
        depends_on:
            - mysql
        links:
          - mysql
        networks:
          - app-network
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
#        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
          - app-network
networks:
  app-network:
    driver: bridge
volumes:
  app: